Repository Team-HandinHand/Side-project-HandinHand, pull requests merged in 2024-12, with the labels that each got.

#9 [Setting] design token 적용
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/GlobalStyle.ts
  src/styles/.gitkeep
Labels: Setting

#12 [Setting] commitlint 세팅 변경
  .commitlintrc.json
  README.md
Labels: Setting

#20 [✨ Feature] 공통컴포넌트-별점, 헤더
  .github/ISSUE_TEMPLATE/html&css.yml
  package-lock.json
  package.json
  src/components/common-ui/header/Header.styles.ts
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/header/header.styled.ts
  src/components/common-ui/star-rating/StarRating.styled.ts
  src/components/common-ui/star-rating/StarRating.tsx
  src/layout/DefaultLayout.tsx
Labels: ✨ Feature

#19 [Feature] 공통컴포넌트작업(포스터박스, 스켈레톤)
  src/components/CommonUI/PosterBox/PosterBox.styled.ts
  src/components/CommonUI/PosterBox/PosterBox.tsx
  src/components/CommonUI/Skeleton/Skeleton.tsx
  src/types/components.ts
Labels: ✨ Feature, 🎨 HTML&CSS

#21 [✨ Feature] 공통컴포넌트- button, input, profile
  public/defaultProfile.jpg
  src/components/common-ui/Button/Button.styles.ts
  src/components/common-ui/Button/Button.tsx
  src/components/common-ui/Input/Input.styles.ts
  src/components/common-ui/Input/Input.tsx
  src/components/common-ui/Profile/Profile.styles.ts
  src/components/common-ui/Profile/Profile.tsx
  src/types/button.ts
  src/types/input.ts
  src/types/profile.ts
Labels: ✨ Feature

#15 [Style]: 메인페이지 레이아웃 작업
  package-lock.json
  package.json
  src/components/home-main/HomeMain.styles.ts
  src/components/home-main/HomeMain.tsx
  src/pages/Home.tsx
  src/routes/router.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#33 [Fix] Router.tsx의 merge 오류 해결
  package-lock.json
  src/components/common-ui/header/Header.tsx
  src/layout/DefaultLayout.tsx
  src/pages/Home.tsx
  src/pages/OtherUserProfilePage.tsx
  src/pages/index.ts
  src/routes/router.tsx
  tsconfig.app.tsbuildinfo
Labels: 🔧 BugFix
