Repository Team-HandinHand/Side-project-HandinHand, pull requests merged in 2025-01, with the labels that each got.

#30 [🎨 HTML&CSS] 영화 상세 페이지 마크업
  src/components/common-ui/star-rating/StarRating.styled.ts
  src/components/common-ui/star-rating/StarRating.tsx
  src/main.tsx
  src/pages/movie-details/MovieDetails.styled.ts
  src/pages/movie-details/MovieDetails.tsx
Labels: 🎨 HTML&CSS

#37 [🎨 HTML&CSS] 즐겨찾기, 보관함 페이지 마크업
  public/image.png
  src/components/bookmark/Bookmark.styles.ts
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/star-rating/StarRating.tsx
  src/components/index.ts
  src/components/reviewedlist/ActiveTab.tsx
  src/components/reviewedlist/MyReviewedList.styles.ts
  src/pages/Bookmark.tsx
  src/pages/ReviewedList.tsx
  src/pages/index.ts
  src/routes/router.tsx
  tsconfig.app.json
Labels: 🎨 HTML&CSS

#25 [🎨 HTML&CSS] 영화, 시리즈 페이지 마크업
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/header/header.styles.ts
  src/components/common-ui/poster/PosterBox.styles.ts
  src/components/common-ui/poster/PosterBox.tsx
  src/components/common-ui/skeleton/Skeleton.tsx
  src/components/common-ui/star-rating/StarRating.styles.ts
  src/components/common-ui/star-rating/StarRating.tsx
  src/components/index.ts
  src/components/movies/MovieFilters.styles.ts
  src/components/movies/MovieFilters.tsx
  src/components/movies/Movies.styles.ts
  src/components/series/Series.styles.ts
  src/main.tsx
  src/pages/Bookmark.tsx
  src/pages/MoviesPage.tsx
  src/pages/SeriesPage.tsx
  src/pages/movie-details/MovieDetails.tsx
  src/types/components.ts
  vite-env.d.ts
  vite.config.ts
Labels: 🎨 HTML&CSS

#39 [🎨 HTML&CSS] 다른 유저 프로필 클릭시 모달 구현
  src/components/common-ui/modal/profile-modal/ProfileModal.styled.ts
  src/components/common-ui/modal/profile-modal/ProfileModal.tsx
Labels: 🎨 HTML&CSS

#26 [🎨 HTML&CSS] 댓글 상세 페이지 마크업
  src/App.tsx
  src/components/comment-detail/CommentDetail.styled.tsx
  src/components/comment-detail/ReviewComment.tsx
  src/components/common-ui/Skeleton/Skeleton.tsx
  src/components/common-ui/poster/PosterBox.styles.ts
  src/components/common-ui/poster/PosterBox.tsx
  src/pages/CommentDetail.tsx
  src/pages/index.ts
  src/routes/router.tsx
  src/types/commentDetail.ts
Labels: 🎨 HTML&CSS

#43 [🎨 HTML&CSS] 검색결과 페이지 마크업
  src/components/index.ts
  src/main.tsx
  src/pages/movie-details/MovieDetails.tsx
  src/pages/movie-search/MovieSearch.styled.ts
  src/pages/movie-search/MovieSearch.tsx
Labels: 🎨 HTML&CSS

#50 [✨ Feature] 포스터목록 컴포넌트화
  src/GlobalStyle.ts
  src/components/bookmark/Bookmark.styles.ts
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/poster/PosterBox.styles.ts
  src/components/common-ui/poster/PosterBox.tsx
  src/components/movieList/MovieList.tsx
  src/components/movies/Movies.styles.ts
  src/components/reviewedlist/MyReviewedList.styles.ts
  src/pages/Bookmark.tsx
  src/pages/MoviesPage.tsx
  src/pages/ReviewedList.tsx
  src/pages/SeriesPage.tsx
  src/types/movieList.ts
Labels: 🎨 HTML&CSS

#47 [✨ Feature] tmdb api type 및 인스턴스 설정
  package-lock.json
  package.json
  src/hooks/queries/useFetchMovies.ts
  src/service/movieApi.ts
  src/types/api.ts
Labels: ✨ Feature

#51 [✨ Feature] 영화 상세 콘텐츠 컴포넌트화
  package-lock.json
  src/components/movie-details/ContentInfo.tsx
  src/components/movie-details/ContentRelated.styled.ts
  src/components/movie-details/ContentRelated.tsx
  src/components/movie-details/MovieDetails.styled.ts
  src/components/movie-search/MovieSearch.styled.ts
  src/pages/MovieDetails.tsx
  src/pages/MovieSearch.tsx
  src/pages/index.ts
  src/pages/movie-details/MovieDetails.tsx
Labels: ✨ Feature

#56 [🔄 Refactor] 로그인 세션 유지
  package-lock.json
  package.json
  src/App.tsx
  src/components/common-ui/Profile/Profile.tsx
  src/components/common-ui/error/Error.styles.ts
  src/components/common-ui/error/Error.tsx
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/profile/Profile.styles.ts
  src/components/edit-profile/EditProfileForm.styles.ts
  src/components/edit-profile/EditProfileForm.tsx
  src/components/media/media-filter/MediaFilter.tsx
  src/components/media/movies/Movies.tsx
  src/components/media/series/Series.tsx
  src/components/sign-in/SignInForm.tsx
  src/components/sign-up/SignUpForm.tsx
  src/constants/media.ts
  src/constants/path.ts
  src/contexts/auth/AuthContext.ts
  src/contexts/auth/AuthProvider.tsx
  src/contexts/auth/index.ts
  src/hooks/mutations/useCheckDuplicate.ts
  src/hooks/mutations/useEditProfile.ts
  src/hooks/mutations/useGoogleSignIn.ts
  src/hooks/mutations/useSignIn.ts
  src/hooks/mutations/useSignOut.ts
  src/hooks/mutations/useSignUp.ts
  src/hooks/mutations/usedeactivateAccount.ts
  src/hooks/queries/useFetchInfiniteMedias.ts
  src/hooks/useAuth.ts
  src/hooks/useAuthStateChange.ts
  src/hooks/useCheckDuplicate.ts
  src/pages/Bookmark.tsx
  src/pages/ReviewedList.tsx
  src/routes/router.tsx
  src/schemas/user/editProfileSchema.ts
  src/stores/userStore.ts
  src/types/auth.ts
  src/types/media.ts
  src/types/user.ts
  supabaseConfig.ts
Labels: 🔄 Refactor

#60 [✨ Feature] 로그인 전 홈페이지 제작
  package-lock.json
  package.json
  src/components/common-ui/poster/PosterBox.styles.ts
  src/components/common-ui/poster/PosterBox.tsx
  src/components/common-ui/tab/Tab.tsx
  src/components/home/home-main/HomeMain.styles.ts
  src/components/home/home-main/HomeMain.tsx
  src/components/home/home-no-auth/HomeNoAuth.styles.ts
  src/components/home/home-no-auth/HomeNoAuth.tsx
  src/components/home/popular-media-slider/PopularMediaSlider.styles.ts
  src/components/home/popular-media-slider/PopularMediaSlider.tsx
  src/components/index.ts
  src/components/media/media-search/MediaSearch.tsx
  src/constants/commonUi.ts
  src/constants/path.ts
  src/hooks/queries/useFetchInfiniteMedias.ts
  src/hooks/queries/useFetchPopularMedia.ts
  src/hooks/useAuthStateChange.ts
  src/pages/HomePage.tsx
  src/pages/MovieSearch.tsx
  src/types/components.ts
  src/types/media.ts
Labels: ✨ Feature

#64 feat: 메인 페이지에서 tmdb api 데이터를 출력 (#58)
  src/components/common-ui/tab/Tab.tsx
  src/components/home/home-main/HomeMain.styles.ts
  src/components/home/home-main/HomeMain.tsx
  tsconfig.app.json
Labels: ✨ Feature

#62 feat: 댓글 상세 페이지 api 연동 작업
  src/components/comment-detail/CommentDetail.styled.tsx
  src/components/comment-detail/CommentPosterBox.tsx
  src/components/comment-detail/ReviewComment.tsx
  src/hooks/queries/useFetchComment.ts
  src/pages/CommentDetail.tsx
  src/routes/router.tsx
  src/service/comments/fetchComment.ts
  src/types/commentDetail.ts
  src/utils/checkIsMovie.ts
  src/utils/getTime.ts
Labels: 📬 API, ✨ Feature

#66 fix: 댓글 관련 쿼리 타입 오류 수정
  src/components/comment-detail/ReviewComment.tsx
  src/hooks/queries/useFetchComment.ts
  src/service/comments/fetchComment.ts
  src/types/commentDetail.ts
Labels: 🔧 BugFix

#71 [✨ Feature] 즐겨찾기, 평가목록 페이지 구현
  src/components/bookmark/Bookmark.styles.ts
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/poster/PosterBox.styles.ts
  src/components/common-ui/tab/Tab.tsx
  src/components/media/Media.styles.ts
  src/components/media/media-list/MediaList.styles.ts
  src/components/media/media-list/MediaList.tsx
  src/components/reviewedlist/MyReviewedList.styles.ts
  src/hooks/mutations/useDeleteReview.ts
  src/pages/Bookmark.tsx
  src/pages/ReviewedList.tsx
  src/routes/router.tsx
  src/service/bookmark/fetchDramaBookmark.ts
  src/service/bookmark/fetchMovieBookmark.ts
  src/service/review/deleteReview.ts
  src/service/review/fetchReview.ts
  src/styles/GlobalStyle.ts
  src/types/media.ts
  src/types/review.ts
Labels: 📬 API, ✨ Feature

#75 [✨ Feature] scroll-to-top 버튼 구현
  src/components/common-ui/scroll-button/index.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#67 [🔄 Refactor] 쿼리들 suspense 적용
  index.html
  src/GlobalStyle.ts
  src/components/comment-detail/CommentDetail.styled.tsx
  src/components/comment-detail/ReviewComment.tsx
  src/components/common-ui/loader/Loader.tsx
  src/components/common-ui/poster/PosterBox.styles.ts
  src/components/common-ui/poster/PosterBox.tsx
  src/components/home/home-main/HomeMain.tsx
  src/components/home/home-no-auth/HomeNoAuth.tsx
  src/components/home/popular-media-slider/PopularMediaSlider.styles.ts
  src/components/media/movies/Movies.tsx
  src/components/sign-in/SignInForm.tsx
  src/components/sign-up/SignUpForm.tsx
  src/hooks/mutations/useEditProfile.ts
  src/hooks/queries/useFetchComment.ts
  src/hooks/queries/useFetchMediaMoreInfo.ts
  src/hooks/useErrorHandler.ts
  src/pages/CommentDetail.tsx
  src/styles/GlobalStyle.ts
  src/styles/designToken.css
  src/types/components.ts
  src/types/database.types.ts
  src/types/media.ts
  supabaseConfig.ts
Labels: 🔄 Refactor

#73 [✨ Feature] 댓글 상세 페이지 수정 및 삭제 로직 적용
  src/components/comment-detail/CommentDetail.styled.tsx
  src/components/comment-detail/CommentEditButton.tsx
  src/components/comment-detail/ReviewComment.tsx
  src/hooks/mutations/useCommentDelete.ts
  src/hooks/mutations/useCommentEdit.ts
  src/utils/toast.ts
Labels: 📬 API, ✨ Feature

#80 [🔄 Refactor] 중복된 toast 함수 제거
  src/components/comment-detail/CommentPosterBox.tsx
  src/components/comment-detail/ReviewComment.tsx
  src/hooks/mutations/useCommentDelete.ts
  src/hooks/mutations/useCommentEdit.ts
  src/hooks/mutations/useDeleteReview.ts
  src/utils/toast.ts
Labels: 🔄 Refactor

#82 [🔄 Refactor] auth context api zustand로 변경
  index.html
  public/Logo.svg
  public/assets/img/test/image.png
  public/vite.svg
  src/App.tsx
  src/assets/img/logo/logo.webp
  src/assets/img/poster/default_poster.webp
  src/assets/img/profile/default_profile.webp
  src/components/comment-detail/CommentEditButton.tsx
  src/components/common-ui/header/Header.tsx
  src/components/common-ui/poster/PosterBox.tsx
  src/components/edit-profile/EditProfileForm.tsx
  src/components/index.ts
  src/components/media/media-search/MediaSearch.tsx
  src/components/media/movies/Movies.tsx
  src/components/media/series/Series.tsx
  src/components/movie-details-comment/commentList.tsx
  src/components/movie-details-comment/commentPosts.tsx
  src/constants/commonUi.ts
  src/constants/media.ts
  src/constants/path.ts
  src/constants/user.ts
  src/contexts/auth/AuthContext.ts
  src/contexts/auth/AuthProvider.tsx
  src/contexts/auth/index.ts
  src/hooks/mutations/useCheckDuplicate.ts
  src/hooks/useAuth.ts
  src/hooks/useAuthStateChange.ts
  src/pages/Bookmark.tsx
  src/pages/HomePage.tsx
  src/pages/ReviewedList.tsx
  src/routes/router.tsx
  src/service/auth/fetchUserProfile.ts
  src/stores/useUserStore.ts
  src/types/auth.ts
Labels: ✨ Feature, 🔄 Refactor

#85 [✨ Feature] 댓글 상세 페이지 시리즈 부분 추가 및 별점 수정 기능 추가
  src/components/comment-detail/ReviewComment.tsx
  src/components/movie-details-comment/commentEdit.tsx
  src/components/movie-details-comment/commentList.tsx
  src/hooks/mutations/useCommentDelete.ts
  src/hooks/mutations/useCommentEdit.ts
  src/hooks/queries/useFetchComment.ts
  src/pages/CommentDetail.tsx
  src/routes/router.tsx
  src/service/comments/deleteDetailsComment.ts
  src/service/comments/fetchComment.ts
  src/service/comments/putDetailsComment.ts
Labels: ✨ Feature, 🔄 Refactor

#84 [🔄 Refactor] activeTab 상태 관리 수정, 메타태그 추가
  index.html
  src/pages/Bookmark.tsx
  src/pages/ReviewedList.tsx
Labels: 🔄 Refactor
